development:
  secret_key_base: 0489b1eaec7de584364cc22365d05d6d8df67ffabac74e43c984bddea1846a60f95d04f629e2010e23ad8269c42d959f617668894e251c5f9b466d40d3fd4236
  GOOGLE_CLIENT_ID:  <%= ENV.fetch("GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_ID") %>
  GOOGLE_CLIENT_SECRET:  <%= ENV.fetch("GOOGLE_CLIENT_SECRET", "GOOGLE_CLIENT_SECRET") %>

test:
  secret_key_base: 9a6ca12cbce71fd7f596c89f5a4d0d545e70c2f12ab5fdccb227a128fa8a1a6bb0860f5bac52af0f25b12f2cd5fc0ac89eb95ae11394eb6ae66766725554a350
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "my-test-secret-key-goes-here") %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "my-production-secret-key-goes-here") %>